#pragma once
#include "BlinnShader.h"
#include "BlinnShader_tangent.h"
#include "ColorShader.h"
#include "RampShader.h"
#include "TexShader.h"
#include "SimpeDepthShader.h"
#include "BlinnShader_shadow.h"
#include "OceanShader.h"